### ISSUE TITLE
修改昨晚找出的管理员端的小bug

### ISSUE THREAD

**Issue by chenliting-123** [mengyunzhi/micro-course#241]
1、登陆时如果已经登陆跳到首页；2、新增完教师和学生之后显示默认密码；3、将工号部分删除，相应查询按照姓名查询；4、在个人中心中增加显示当先用户信息；5、教师登录后增加管理员权限判断；6、通过字段判断是否为管理员；7、统一学期状态的颜色；8、修改学期激活或者冻结成功后的提示；9、修改查看模板的样式；10、查看座位图模板时改掉循环显示；11、重设模板点击提交按钮之后再进行删除；11、在模板查看的时候添加返回按钮；12、将教师编辑和模板查看相统一；13、 二维码打印时格式问题，要按照A4纸打印

**Comment by teacherpan** [comment]
每条建成一个issue，更好

**Comment by chenliting-123** [comment]
收到
