### ISSUE TITLE
问题：多对多调用信息

### ISSUE THREAD

**Issue by haozelong** [mengyunzhi/micro-course#29]
分支四，course控制器第34行为啥调用Students方法为啥不是Students()

**Comment by wenyuhang666** [comment]
获取器的问题，这种方法的实现应该在你的M层有获取器，具体知识点详见
教程https://www.kancloud.cn/yunzhiclub/thinkphp5guide/168933
官方文档https://www.kancloud.cn/manual/thinkphp5/135192
