### ISSUE TITLE
分支合并

### ISSUE THREAD

**Issue by wenyuhang666** [mengyunzhi/micro-course#33]
目前主分支的代码是分开的，我跟陈丽婷的代码是放到了thinkphp5整个的模板当中，目前数据库的整体搭建已经大致完成，我觉得两个主要分支可以把现有的能用的功能合并到一起，并且希望主分支的代码都放到thinkphp5中，以便于整体操作

**Comment by teacherpan** [comment]
@haozelong @wenyuhang666 @chenliting-123 此问题需要优先解决，代码上看才像一个团队在开发。
